import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";

const onest = Onest({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["cyrillic", "latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <script
                async
                src="https://telegram.org/js/telegram-web-app.js"
            ></script>
            <body className={onest.className}>{children}</body>
        </html>
    );
}
